name: storyblok
description: A client for storyblok.
# version: 1.0.0
# homepage: https://github.com/md-weber/storyblok

environment:
  sdk: '>=2.7.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.2
